server {
    listen 80;
    listen [::]:80;

    server_name 206.189.15.67 bunq-yaai.ddns.net; # Replace with your actual domain name

    proxy_read_timeout 600s;

    location / {
        try_files $uri @proxy_api;
    }

    location @proxy_api {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://frontend:3000;
    }

    location /backend/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Use a trailing slash for consistency
        proxy_pass http://backend:8080/;
    }

    location /minio/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Use a trailing slash for consistency
        proxy_pass http://minio:9000/;
    }
}
